#pragma config(Sensor, in2,    lineFollower,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumpSensor,    sensorTouch)
#pragma config(Motor,  port1,   leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,   rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,   armMotor,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Constants
const int servoChangeRate = 1;
const int controlLoopDelay = 25;
const float accelerationStep = 0.1;
const int targetValue = 2300;

// Variables for tank control smoothing
float leftMotorSpeed = 0;
float rightMotorSpeed = 0;

// Variables for debouncing button presses
bool btn5UPressedLastCycle = false;
bool btn5DPressedLastCycle = false;
bool btn6UPressedLastCycle = false;

int armMotorPosition = 0;

// Line follower PID constants
float Kp = 0.2;
float Ki = 0;
float Kd = 0;

// Line follower variables
int error = 0;
int errorDist = 0;
int integral = 0;
int derivative = 0;
int lastError = 0;
bool lineFollowerActive = true;

task ArmControl() {
	while(true) {
		// Increment arm position if button 5U is pressed
		if (vexRT[Btn5U] && !btn5UPressedLastCycle) {
			armMotorPosition += servoChangeRate;
			btn5UPressedLastCycle = true;
			} else if (!vexRT[Btn5U]) {
			btn5UPressedLastCycle = false;
		}

		// Decrement arm position if button 5D is pressed
		if (vexRT[Btn5D] && !btn5DPressedLastCycle) {
			armMotorPosition -= servoChangeRate;
			btn5DPressedLastCycle = true;
			} else if (!vexRT[Btn5D]) {
			btn5DPressedLastCycle = false;
		}

		// Limit the arm motor position to valid range of -127 to 127
		armMotorPosition = armMotorPosition > 127 ? 127 : armMotorPosition < -127 ? -127 : armMotorPosition;

		// Write the position to the arm motor
		motor[armMotor] = armMotorPosition;

		wait1Msec(controlLoopDelay);
	}
}

task LineFollower() {
	while(true) {
		if(lineFollowerActive) {
			// Line following logic goes here
			error = SensorValue[lineFollower] - targetValue;
			integral = integral + error;
			derivative = error - lastError;
			lastError = error;

			// Prevent integral windup
			errorDist = abs(error);
			if (errorDist < targetValue) {
				integral += error;
				} else {
				integral = 0; // Reset integral if error is too large
			}
			if (integral > 4000) {
				integral = 0;
			}

			//leftMotorSpeed = Kp * error + Ki * integral + Kd * derivative;
			//rightMotorSpeed = leftMotorSpeed;

			// Calculate motor power, ensuring it does not exceed the motor's limits
			int motorPowerLeft = Kp * error + Ki * integral + Kd * derivative;
			int motorPowerRight = Kp * error - Ki * integral - Kd * derivative;

			// Clamp the motor power to the max and min motor power range
			motorPowerLeft = motorPowerLeft > 127 ? 127 : motorPowerLeft < -127 ? -127 : motorPowerLeft;
			motorPowerRight = motorPowerRight > 127 ? 127 : motorPowerRight < -127 ? -127 : motorPowerRight;

			// If bump sensor is pressed, stop the motors
			if(SensorValue[bumpSensor] == 1) {
				motorPowerLeft = 0;
				motorPowerRight = 0;
			}

			motor[leftMotor] = motorPowerLeft;
			motor[rightMotor] = motorPowerRight;
		}

		wait1Msec(controlLoopDelay);
	}
}

task main() {
	startTask(ArmControl);
	startTask(LineFollower);

	while(true) {
		// Tank control logic goes here
		if (vexRT[Btn6U] && !btn6UPressedLastCycle) {
			//lineFollowerActive = !lineFollowerActive;
			btn6UPressedLastCycle = true;
			} else if (!vexRT[Btn6U]) {
			btn6UPressedLastCycle = false;
		}

		if(!lineFollowerActive) {
			// Smooth acceleration for tank control
			// Left motor
			float leftJoystick = vexRT[Ch3];
			float rightJoystick = vexRT[Ch2];
			if(abs(leftJoystick - leftMotorSpeed) > accelerationStep) {
				leftMotorSpeed += (leftJoystick > leftMotorSpeed) ? accelerationStep : -accelerationStep;
				} else {
				leftMotorSpeed = leftJoystick;
			}

			// Right motor
			if(abs(rightJoystick - rightMotorSpeed) > accelerationStep) {
				rightMotorSpeed += (rightJoystick > rightMotorSpeed) ? accelerationStep : -accelerationStep;
				} else {
				rightMotorSpeed = rightJoystick;
			}

			// Set motor speeds
			motor[leftMotor] = leftMotorSpeed;
			motor[rightMotor] = rightMotorSpeed;
		}

		wait1Msec(controlLoopDelay);
	}
}
