#pragma config(Sensor, in1,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, in2,    lineTrackerCenter, sensorLineFollower)
#pragma config(Sensor, in3,    lineTrackerLeft, sensorLineFollower)
#pragma config(Motor,  port1,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(1000);          // wait 1 seconds before starting.

	int threshold = 2400;// found by taking a reading on both DARK and LIGHT surfaces, adding them together, then dividing by 2.

	// start line following
	while(true)
	{
    // RIGHT sensor trigger:
    if(SensorValue(lineTrackerRight) > threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 63;
      motor[rightMotor] = 0;
    }
    // CENTER sensor trigger:
    if(SensorValue(lineTrackerCenter) > threshold)
    {
      // go straight
      motor[leftMotor]  = 63;
      motor[rightMotor] = 63;
    }
    // LEFT sensor trigger:
    if(SensorValue(lineTrackerLeft) > threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }
  }
	//wait1Msec(10);
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
